# This file is a template, and might need editing before it works on your project.
# Template project: https://gitlab.com/pages/jekyll
# Docs: https://docs.gitlab.com/ce/pages/
image: alpine:latest

pages:
  stage: deploy
  script:
  - echo 'Nothing to do ...'
  artifacts:
    paths:
    - public
  only:
    - master