# This file is a template, and might need editing before it works on your project.
# Template project: https://gitlab.com/pages/jekyll
# Docs: https://docs.gitlab.com/ce/pages/
image: ruby:2.3

pages:
  stage: deploy
  script:
  - /bin/true
  artifacts:
    paths:
    - public
  only:
    - master
  tags:
    - pages
